KYV-839: add payment gateway to subscription
City-of-Helsinki/verkkokauppa-core pull request #300
Opened 2023-03-08 09:08 UTC by wpamb

2023-03-08 15:52 UTC, severikupari1 commented on orderapi/src/main/java/fi/hel/verkkokauppa/order/model/subscription/Subscription.java
> +	@Field(type = FieldType.Text)
This type should be Keyword

2023-03-08 16:01 UTC, severikupari1 requested changes
Some minor changes

2023-03-09 06:36 UTC, laukkanenj approved these changes

2023-03-10 07:20 UTC, severikupari1 approved these changes
Good job!

2023-03-14 02:18 UTC, merged