KYV-870: set subscription card on card update redirect
City-of-Helsinki/verkkokauppa-core pull request #316
Opened 2023-05-11 20:06 UTC by wpamb

2023-05-14 09:43 UTC, severikupari1 requested changes

2023-05-14 09:43 UTC, severikupari1 commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/PaytrailPaymentController.java
> +                merchantId = dto.getOrder().getItems().get(0).getMerchantId();
You should create helper function to get merchant is from order, we have service/util class functionality in controller now.

2023-05-14 09:43 UTC, severikupari1 commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/PaytrailPaymentController.java
> +            log.error("checking card update return response failed", e);
Add paytrail to error

2023-05-23 04:51 UTC, laukkanenj approved these changes

2023-05-24 06:28 UTC, severikupari1 approved these changes

2023-05-25 13:18 UTC, merged