KYV-265
City-of-Helsinki/verkkokauppa-core pull request #34
Opened 2021-09-27 10:49 UTC by severikupari1

feat:Changed orderItem and OrderItemMetaD id creation to use "real" uuid. Created automation tests to assert that created id:s should not match.
removed: Removed removeItem function which was not used anywhere and cant be used anymore.

Signed-off-by: severikupari1 <severikupari1@gmail.com>

2021-09-27 13:29 UTC, hleisma requested changes

2021-09-27 13:29 UTC, hleisma commented on productapi/src/main/resources/application-local.properties
> +Delasticsearch.service.url=localhost:9200
minor typo here

2021-09-28 08:01 UTC, severikupari1 commented on productapi/src/main/resources/application-local.properties
> +Delasticsearch.service.url=localhost:9200
Fixed typo

2021-09-28 08:35 UTC, eerohakio approved these changes

2021-09-28 08:38 UTC, merged