KYV-891: implement create invoice payment and its url
City-of-Helsinki/verkkokauppa-core pull request #343
Opened 2023-09-26 14:59 UTC by wpamb

2023-09-27 09:16 UTC, laukkanenj commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/service/InvoicePaymentService.java
> +        return env.getRequiredProperty("invoice_payment_url") + "?orderId=" + payment.getOrderId() + "&user=" + payment.getUserId();
Onko tuo 'invoice_payment_url' jo määritelty jonnekin? Ei sattunut silmään mistään

2023-10-11 13:11 UTC, wpamb commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/service/InvoicePaymentService.java
> +        return env.getRequiredProperty("invoice_payment_url") + "?orderId=" + payment.getOrderId() + "&user=" + payment.getUserId();
Nyt on

2023-10-13 03:30 UTC, laukkanenj commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/service/InvoicePaymentService.java
> +        return env.getRequiredProperty("invoice_payment_url") + "?orderId=" + payment.getOrderId() + "&user=" + payment.getUserId();
Voisitko vielä laittaa application-local.properties tiedostoon semmoisen arvon jonka pitäisi toimia lokaalissa?

2023-10-13 03:39 UTC, laukkanenj requested changes
'invoice_payment_url' vielä application-local.properties tiedostoon

2023-10-13 11:25 UTC, laukkanenj approved these changes

2023-10-25 13:54 UTC, merged