Feature/kyv 1123 free payment refund success controller
City-of-Helsinki/verkkokauppa-core pull request #442
Opened 2024-12-30 13:18 UTC by laukkanenj

2025-01-02 13:48 UTC, severikupari1 commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/FreeRefundPaymentController.java
> +            RefundPayment refundPayment = freeRefundPaymentService.getRefundPaymentWithRefundId(refundId);
shoul this be with refundPaymentId?

2025-01-02 13:50 UTC, severikupari1 requested changes
Check the one comment

2025-01-07 05:31 UTC, laukkanenj commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/FreeRefundPaymentController.java
> +            RefundPayment refundPayment = freeRefundPaymentService.getRefundPaymentWithRefundId(refundId);
Here we don't know what the refund payment ID is, similar to how this is done with paytrail refunds

2025-01-07 05:36 UTC, laukkanenj commented on paymentapi/src/main/java/fi/hel/verkkokauppa/payment/api/FreeRefundPaymentController.java
> +            RefundPayment refundPayment = freeRefundPaymentService.getRefundPaymentWithRefundId(refundId);
Maybe both need to be fixed

2025-01-07 07:24 UTC, severikupari1 approved these changes

2025-01-07 07:25 UTC, merged