Feature/kyv 393 right of purchase
City-of-Helsinki/verkkokauppa-core pull request #92
Opened 2021-11-17 07:35 UTC by severikupari1

2021-11-17 07:36 UTC, severikupari1 commented on common/src/main/java/fi/hel/verkkokauppa/common/rest/RestServiceClient.java
> +        if (response == null) {
These fixes NullPointerExceptions

2021-11-17 15:07 UTC, hleisma requested changes
Avoid chaining throws JsonProcessingException, that just makes your problem somebody elses problem. We have agreed that REST endpoints only return structured error messages, not ok to let an exception through.

2021-11-18 07:55 UTC, severikupari1 commented on orderapi/src/main/java/fi/hel/verkkokauppa/order/api/SubscriptionAdminController.java
> +    public ResponseEntity<Void> subscriptionRenewalRequestedEventCallback(@RequestBody SubscriptionMessage message) throws JsonProcessingException {
I will fix these error throwings. Good to know to catch all errors and just log and change http status. Good points, thanks for review!

2021-11-18 10:45 UTC, severikupari1 commented on orderapi/src/main/java/fi/hel/verkkokauppa/order/api/SubscriptionAdminController.java
> +    public ResponseEntity<Void> subscriptionRenewalRequestedEventCallback(@RequestBody SubscriptionMessage message) throws JsonProcessingException {
Now this is fixed.

2021-11-18 10:45 UTC, merged